from sqlalchemy import BigInteger, Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship

from app.db.database import Base

class Attachment(Base):
    __tablename__ = "attachments"

    id = Column(Integer, primary_key=True, index=True)
    message_id = Column(Integer, ForeignKey("messages.id"), nullable=True)  # Nullable для DM
    dm_message_id = Column(Integer, ForeignKey("direct_messages.id"), nullable=True)  # Для DM
    # Legacy uploads use file_url. Managed webhook files use storage_key and a
    # short-lived signed URL generated by the message serializer.
    file_url = Column(String, nullable=True)
    original_filename = Column(String(255), nullable=True)
    content_type = Column(String(255), nullable=True)
    size_bytes = Column(BigInteger, nullable=True)
    storage_key = Column(String(512), nullable=True, unique=True, index=True)
    sha256 = Column(String(64), nullable=True)
    description = Column(String(1024), nullable=True)
    
    message = relationship("Message", back_populates="attachments")
    dm_message = relationship("DirectMessage", back_populates="attachments") 
